import type { Raffle, Participant } from './types';

export const participants: Participant[] = [
  { id: '1', name: 'Alice Johnson', email: 'alice@example.com' },
  { id: '2', name: 'Bob Williams', email: 'bob@example.com' },
  { id: '3', name: 'Charlie Brown', email: 'charlie@example.com' },
  { id: '4', name: 'Diana Miller', email: 'diana@example.com' },
  { id: '5', name: 'Ethan Davis', email: 'ethan@example.com' },
  { id: '6', name: 'Fiona Garcia', email: 'fiona@example.com' },
  { id: '7', name: 'George Rodriguez', email: 'george@example.com' },
  { id: '8', name: 'Hannah Martinez', email: 'hannah@example.com' },
  { id: '9', name: 'Ian Hernandez', email: 'ian@example.com' },
  { id: '10', name: 'Jane Lopez', email: 'jane@example.com' },
  { id: '11', name: 'Kevin Gonzalez', email: 'kevin@example.com' },
  { id: '12', name: 'Laura Wilson', email: 'laura@example.com' },
  { id: '13', name: 'Mason Anderson', email: 'mason@example.com' },
  { id: '14', name: 'Nora Thomas', email: 'nora@example.com' },
  { id: '15', name: 'Oscar Taylor', email: 'oscar@example.com' },
  { id: '16', name: 'Penelope Moore', email: 'penelope@example.com' },
  { id: '17', name: 'Quinn Jackson', email: 'quinn@example.com' },
  { id: '18', name: 'Ryan White', email: 'ryan@example.com' },
  { id: '19', name: 'Sophia Harris', email: 'sophia@example.com' },
  { id: '20', name: 'Tyler Martin', email: 'tyler@example.com' },
];

export const raffles: Raffle[] = [
  {
    id: '1',
    title: 'Annual Grand Prize Raffle',
    description: 'Our biggest raffle of the year with amazing prizes.',
    status: 'Active',
    totalParticipants: 150,
    totalWinners: 5,
    participants: participants,
    winners: [],
  },
  {
    id: '2',
    title: 'Q2 Tech Giveaway',
    description: 'Win the latest gadgets in our quarterly tech draw.',
    status: 'Draft',
    totalParticipants: 200,
    totalWinners: 10,
    participants: [],
    winners: [],
  },
  {
    id: '3',
    title: 'Holiday Special 2023',
    description: 'A festive raffle to celebrate the holiday season.',
    status: 'Completed',
    totalParticipants: 100,
    totalWinners: 3,
    participants: [],
    winners: [
      { id: '21', name: 'Winner One', email: 'winner1@example.com' },
      { id: '22', name: 'Winner Two', email: 'winner2@example.com' },
      { id: '23', name: 'Winner Three', email: 'winner3@example.com' },
    ],
  },
    {
    id: '4',
    title: 'New Year Kick-off',
    description: 'Start the new year with a bang!',
    status: 'Active',
    totalParticipants: 300,
    totalWinners: 15,
    participants: [],
    winners: [],
  },
];
